name: Update Aura Badge
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5 # Updated version
        with:
          python-version: '3.x'
      - name: Run Script
        run: python main.py
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add aura.svg streak.txt  # Added streak.txt here!
          git commit -m "update: focus streak" || exit 0
          git push
